beta/urls.py
from django.urls import path

from . import views

app_name = 'beta'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('location/<int:location_id>/', views.LocationAreaList.as_view(), name='location'),
    path('area/<int:area_id>/', views.AreaRouteList.as_view(), name='area'),
    path('route/<int:route_id>/', views.RouteDetailList.as_view(), name='route'),
    path('beta_detail/<int:beta_id>/', views.beta_detail, name='beta_detail'),
]

ezbeta/ezbeta/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ezbeta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('beta/',  include('beta.urls')),
    path('admin/', admin.site.urls),
]

beta/models.py
import datetime

from django.db import models
from django.utils import timezone
from collections import namedtuple

# Create your models here.

class Location(models.Model):
    ''' Describes the location where the climbing routes are located.
    This will include long/lat coordinates, and will be able to be searched
    by proximity '''
    location_name = models.CharField(max_length=50, default='Missing location name')
    location_desc = models.CharField(max_length=500, default='')
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)

    def __str__(self):
        return self.location_name

class Area(models.Model):
    ''' Describes the sublocations within a Location. For example,
    in a boulder field, this might refer to individual boulders. '''
    
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    area_name = models.CharField(max_length=50, default='')
    area_desc = models.CharField(max_length=500, default='')
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=0.0)
    def __str__(self):
        return self.area_name

class Route(models.Model):
    ''' Describes physical routes on the area '''
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    route_name = models.CharField(max_length=50, default='')
    setter_name = models.CharField(max_length=100, default='')
    grade = models.IntegerField(default=0)
    rating = models.IntegerField(default=0)
    set_date = models.DateTimeField('date set', default = timezone.now)
    def __str__(self):
        return self.route_name

class Beta(models.Model):
    ''' Describes one way to do the beta for a specific route '''
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    beta_name = models.CharField(max_length=50, default='')
    beta_desc = models.CharField(max_length=500, default='')
    quality_rating = models.IntegerField(default=0)
    creator_name = models.CharField(max_length=50, default='')
    set_date = models.DateTimeField('date set', default = timezone.now)
    def __str__(self):
        return self.beta_name

beta/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Location, Area, Route, Beta
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'beta/index.html'
    context_object_name = 'location_list'

    # I want to eventually get the nearest locations based on long/lat to the current position
    # and list the top 5
    def get_queryset(self):
        return Location.objects.all()

class LocationAreaList(generic.ListView):
    
    template_name = 'beta/area.html'
    context_object_name = 'area_list' 

    def get_queryset(self):
        self.location = get_object_or_404(Location, pk=self.kwargs['location_id'])
        return Area.objects.filter(location=self.location)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = self.location
        return context

class AreaRouteList(generic.ListView):

    template_name = 'beta/route.html'
    context_object_name = 'route_list'

    def get_queryset(self):
        self.area = get_object_or_404(Area, pk=self.kwargs['area_id'])
        return Route.objects.filter(area=self.area, set_date__lte=timezone.now())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['area'] = self.area
        context['location'] = self.area.location
        return context

class RouteDetailList(generic.ListView):

    template_name = 'beta/beta.html'
    context_object_name = 'beta_list'
    
    def get_queryset(self):
        self.route = get_object_or_404(Route, pk=self.kwargs['route_id'])
        return Beta.objects.filter(route=self.route, set_date__lte=timezone.now())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = self.route.area.location
        context['area'] = self.route.area
        context['route'] = self.route
        context['grade'] = self.route.grade
        context['rating'] = self.route.rating
        context['set_date'] = self.route.set_date
        context['now'] = timezone.now()
        return context


def beta_detail(request, beta_id):
    beta = get_object_or_404(Beta, pk=beta_id, set_date__lte=timezone.now())
    return render(request, 'beta/beta_detail.html', {'beta': beta})
    

beta/templates/beta/area.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'beta/style.css' %}" />
<title> ezbeta: {{ location.location_name }} </title>
<strong>{{ location.location_name }}</strong>
{% if area_list %}
  <ul>
  {% for area in area_list %}
    <li><a href="{% url 'beta:area' area.id %}">{{ area.area_name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No areas are available.</p>
{% endif %}

beta/templates/beta/beta.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'beta/style.css' %}" />
<title> ezbeta: {{ location.location_name }} </title>
<strong>{{ location.location_name }}: {{area.area_name}}: {{route.route_name}}</strong>
{% if set_date <  now %}
    <ul>
      <a>Set Date: {{ set_date }}</a>
      <p>Grade: V{{ grade }}</a></p>
      <p>Rating: {{ rating }}</a></p>
    </ul>
  {% if beta_list %}
    <ul>
    {% for beta in beta_list %}
      <li><a href="{% url 'beta:beta_detail' beta.id %}">{{ beta.beta_name }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No betas are available.</p>
  {% endif %}
{% else %}
    <p>This route is not set yet.</p>
{% endif %}

beta/templates/beta/beta_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'beta/style.css' %}" />
{% if beta %}
  <strong>{{ beta.beta_desc }} </strong>
{% else %}
  <p>No routes are available.</p>
{% endif %}

beta/templates/beta/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'beta/style.css' %}" />
<title> ezbeta </title>
<strong> EZBETA </strong>
<p> Locations: </p>
{% if location_list %}
  <ul>
  {% for location in location_list %}
    <li><a href="{% url 'beta:location' location.id %}">{{ location.location_name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No locations are available.</p>
{% endif %}

beta/templates/beta/route.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'beta/style.css' %}" />
<title> ezbeta: {{ location.location_name }} </title>
<strong>{{ location.location_name }}: {{area.area_name}}</strong>
<p> Long, Lat: {{area.longitude}}, {{area.latitude}} </p>
<p> {{area.area_desc}} </p>
{% if route_list %}
  <ul>
  {% for route in route_list %}
    <li><a href="{% url 'beta:route'  route.id %}">{{ route.route_name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No routes are available.</p>
{% endif %}